name: TimberCraft
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#443635'
    - '#f5b321'
    - '#9e7532'
    - '#a09b98'
  brandStrength: 0.26985871721990407
  lightness: 0.5304859085008502
  saturation: 0.4808209598995745
  rhythmicContrast: 0.3251770241186023
purpose: []
