name: TimberCraft
favicon: null
layout_spectrum: 0.746281961677596
typography_spectrum: 0.380209153983742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.26985871721990407
  lightness: 0.5304859085008502
  saturation: 0.4808209598995745
  rhythmicContrast: 0.3251770241186023
purpose: []
